<div class="masthead">
    <h1 class="muted">Wildwood Wolves Basketball</h1>
    <div class="navbar navbar-default">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">Wolves</a></li>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Expectations <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="expectations-player.html">Players</a></li>
                    <li><a href="expectations-coach.html">Coaches</a></li>
                    <li><a href="expectations-parents.html">Parents</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Expectations <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="expectations-player.html">Players</a></li>
                    <li><a href="expectations-coach.html">Coaches</a></li>
                    <li><a href="expectations-parents.html">Parents</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Calendars <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="calendar-fourth.html">4th Grade</a></li>
                    <li><a href="calendar-seventh.html">7th Grade</a></li>
                </ul>
            </li>
            <li><a href="plays.html">Plays</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Statistics <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="stats-fourth.html">4th Grade</a></li>
                    <li><a href="stats-seventh.html">7th Grade</a></li>
                </ul>
            </li>
        </ul>
        <!-- <form class="navbar-form navbar-left">
            <input type="text" class="form-control col-lg-8" placeholder="Search">
        </form> -->
        <ul class="nav navbar-nav navbar-right">
            <li><a href="news.html">News <span class="badge badge-important">!</span></a></li>
        </ul>
        </div>
    </div>
</div>